### ISSUE TITLE
[BUG] Symbol.asyncIterator is not defined.

### ISSUE THREAD

**Issue by dianbagus96** [ScriptSmith/instamancer#1]
i got this error when i run this comment instamancer hashtag instagood -d, any help for this kind of error ?

**Comment by ScriptSmith** [comment]
I believe this is because the version of Node you're using is not up to date. What version of Node, NPM, and Instamancer are you using?

**Comment by dianbagus96** [comment]
hi @ScriptSmith ,
im using node v8.0.10.0  and npm version 5.6

![image](https://user-images.githubusercontent.com/5764550/54112437-bc443000-4418-11e9-8f95-3ee0ee61a935.png)

**Comment by dianbagus96** [comment]
hi @ScriptSmith ,
im using node v8.0.10.0  and npm version 5.6
![image](https://user-images.githubusercontent.com/5764550/54112522-f1e91900-4418-11e9-88ef-e4fa80414962.png)

**Comment by dianbagus96** [comment]
sorry, im update node to version 10 and the error has gone, thanks @ScriptSmith

**Comment by ScriptSmith** [comment]
No worries
