### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by ArnaudJeannin** [ScriptSmith/instamancer#12]
Is it possible to get the user's most recent media only?

**Comment by ScriptSmith** [comment]
I'm not sure what you mean. Are you trying to get a user's most recent
post, of the oldest available one?

**Comment by ArnaudJeannin** [comment]
> I'm not sure what you mean. Are you trying to get a user's most recent post, of the oldest available one?

Yes

**Comment by ScriptSmith** [comment]
Then I think this is a duplicate of #3 

You need to use `instamancer user [username] -c1 -d --full`.

Follower usernames isn't something that instamancer can do, but there are probably other tools that will work.
