### ISSUE TITLE
[BUG] Locations are not supported any more

### ISSUE THREAD

**Issue by goooseman** [ScriptSmith/instamancer#17]
**Describe the bug**
Instagram has made `/explore/locations` to be available only to logged-in users.

`https://www.***.com/explore/locations/212988663` - here is the route, which is used by Instamancer. If you will open this route in your browser - it will ask to log in.

**To Reproduce**
`instamancer location 212988663`

OR

`npm test -- -t "Library Classes"`

**Expected behavior**
Location photos to be found

**Output**

```
 ● Library Classes › location

    expect(received).toBe(expected) // Object.is equality

    Expected: 10
    Received: 0
```

**Comment by goooseman** [comment]
There is nothing we can do, unfortunately.

I can create a PR to remove this functionality and the tests, if you approve it.

**Comment by ScriptSmith** [comment]
Damn. Thanks for spotting this. I'll give it 24 hours, then I'll remove it myself.

**Comment by ScriptSmith** [comment]
The build history matches the timeline of this: https://www.businessinsider.com.au/startup-hyp3r-saving-instagram-users-stories-tracking-locations-2019-8?r=US&IR=T

**Comment by karimkairo** [comment]
Hi, does this mean that instamancer can no longer scrape location data or do we just need to login; i.e. I wont be able to run this via instaphyte:
instaphyte location 212988663 -c 200 --filetype csv

**Comment by ScriptSmith** [comment]
Because instamancer and instaphyte are intended for _public_ data scraping, they cannot support location scraping because it is only available through signed-in accounts.

I've checked and the methods used by instamancer and instaphyte would both work with signed in accounts. They're released under the MIT license so you are allowed to copy both of these projects and modify them to work with signed-in accounts, however I cannot condone or support such usage.

**Comment by karimkairo** [comment]
Really appreciate the fast response. I understand that both scripts use
public data, is there an option (or non-developer) setting I can implement
to add in the login functionality, with the basic end result I used to get
a month back before the IG restrctions?

**Comment by ScriptSmith** [comment]
Currently there is no way of doing this without writing some code yourself. For instaphyte I think the only difference would be that you'd need to use cookies when requesting data from the API [here](https://github.com/ScriptSmith/instaphyte/blob/c0c0e9dc4c2e005b36abba32246716983e92617d/instaphyte/api.py#L18-L19).

Surprisingly I couldn't find other tools that use the same API for locations as instaphyte so I don't think I can point you somewhere else.

In the future I'd consider adding a plugin system to instamancer allowing developers to listen for events that the scraper dispatches and implement extra functionality. However I think I'd need some other use-cases to consider adding that

**Comment by ScriptSmith** [comment]
Actually, instaloader does support signed-in location scraping. I'm not sure if it uses the same method that instaphyte did, but it should work.

**Comment by karimkairo** [comment]
Thanks Adam
Cant personally confirm instaloader. But managed to get signed in location
scraping from instagram-scraper:
*instagram-scraper -u USERNAME -p PASSWORD --location LOCATION_ID -m
MAX_COUNT -t none --media-metadata*
Ill revert back if I give instaloader a shot, and thanks again Adam

**Comment by ScriptSmith** [comment]
No worries, happy to help
