### ISSUE TITLE
[BUG] Cannot Install Using Repository

### ISSUE THREAD

**Issue by Bongani** [ScriptSmith/instamancer#18]
**Describe the bug**
Instammacer installation fails as it is unable to find the _cli.js_ file. I took a look at the folder, and I find a _cli.ts_file instead. Screenshot of error provided below:

![image](https://user-images.githubusercontent.com/1842813/62871270-81be2680-bd1b-11e9-93c4-e92bdd08cb7b.png)

**Setup**
 - OS: [Ubuntu 19.04]
 - Instamancer version [master]
 - Node version [v10.15.3]
 - NPM version (if applicable) [ 6.4.1]

**Additional context**

**Comment by ScriptSmith** [comment]
Seems this was introduced by db0a3e1d7be5e80658413e1c8bb76995cfcb9264

**Comment by ScriptSmith** [comment]
See the [updated instructions](https://github.com/ScriptSmith/instamancer/blob/master/README.md#from-this-repository)
