### ISSUE TITLE
[FEATURE] Ability to scrape tagged users

### ISSUE THREAD

**Issue by Daniel-Griffiths** [ScriptSmith/instamancer#25]
Some users on instagram have a tab for viewing anyone that has tagged them, for example: https://www.instagram.com/instagram/tagged/?hl=en

It would be great if Instamancer could scrape posts from this page, similar to how the hashtag scraping works.

PS: Thanks for all the hard work you guys have done on Instamancer! 😄

**Comment by Daniel-Griffiths** [comment]
Hey @ScriptSmith! From my testing this does seem to work with any Instagram account. Here are a few more examples I found:

https://www.instagram.com/nintendo/tagged/?hl=en
https://www.instagram.com/ubisoft/tagged/?hl=en
https://www.instagram.com/pokemon/tagged/?hl=en

What I have discovered is that if you browse Instagram and click the "Tagged" button it prompts you to login, but if you access the link directly then it works without being logged in.

So in theory `https://www.instagram.com/${username}/tagged/?hl=en` should work for any account.

**Comment by ScriptSmith** [comment]
Ah, cool! Thanks for letting me know, I probably wouldn't have figured that out.

I'll try get it into Instamancer over the weekend

**Comment by ScriptSmith** [comment]
Seems to work as expected. It just has some different post structures that will need to be added to the validator. 

You can clone the repo and use `instamancer tagged [id]` if you want to try it out.

**Comment by Daniel-Griffiths** [comment]
Oh wow that was so fast! Thanks so much for adding this in!

I was try this new feature out this weekend and see how it goes. 😄

**Comment by ScriptSmith** [comment]
It seems that this is now impossible without signing in

**Comment by Daniel-Griffiths** [comment]
Thanks for the heads up @ScriptSmith! 

It looks like Instagram are really cracking down on scraping. :cry:
