### ISSUE TITLE
One file for all scraps

### ISSUE THREAD

**Issue by ArnaudJeannin** [ScriptSmith/instamancer#28]
I'm using batchfile to scrap multi accounts, is it possible to download one json file at the end of all scaps instead a file by username ?

**Comment by ScriptSmith** [comment]
This would be challenging to add because instamancer doesn't currently use line-delimited JSON.

It's simple to combine json files with something like jq:

```
jq -s '[.[][]]' *.json > output
```

**Comment by ScriptSmith** [comment]
So the entire pattern could be something like:

Create storage dir
```
mkdir users
```

Write `batch.txt`
```txt
user -c10 therock -o "users/[id].json"
user -c10 arianagrande -o "users/[id].json"
```

Retrieve and combine output:
```
instamancer batch batch.txt && jq -s '[.[][]]' *.json > users.json
```

**Comment by ScriptSmith** [comment]
So the entire pattern could be something like:

Create storage dir
```
mkdir users
```

Write `batch.txt`
```txt
user -c10 therock -o "users/[id].json"
user -c10 arianagrande -o "users/[id].json"
```

Retrieve and combine output:
```
instamancer batch batch.txt && jq -s '[.[][]]' users/*.json > users.json
```
