### ISSUE TITLE
Instgram login pops up and scraping freezes [BUG - possibly...?]

### ISSUE THREAD

**Issue by Rosie-Brigham** [ScriptSmith/instamancer#36]
Instamancer has been working like a dream for me up until last week. Now, after it has scraped roughly 21 images, Chromium opens the 'please login to instagram' window and scraping stops.

Left alone this will just sleep and re-sleep, and I have to manually exit the process. If I try to login to the modal on Chromium it also does nothing.

Has there been any changes? Or am I doing something wrong.

this is the command I have been using:
`instamancer hashtag castlesemple --full --logging=info --visible`

Mac Mojave, npm version 6.12.1

**Comment by ScriptSmith** [comment]
What version of instamancer are you using? The latest version (v3.0.1) should no longer have this problem.
