### ISSUE TITLE
Omitting fullAPI skips first 12 posts

### ISSUE THREAD

**Issue by jasondibenedetto** [ScriptSmith/instamancer#39]
Currently having an issue when running the `user` command. The resulting data that is generated skips the first 12 posts on the user's timeline. 

For example, the posts that are retrieved from the following commands are different...

```
# skips first 12 results
npx instamancer user nintendo  --count 24 --type csv


# successfully gets first 12 results
npx instamancer user nintendo  --count 24 --type csv --full
```

**Comment by ScriptSmith** [comment]
This is intentional, as the first 12 posts are embedded in the page, rather than generated from an API request.

We could try reading the initial posts from `window._sharedData`, but I'm not yet confident that retrieving posts from memory will be consistent in the future.

**Comment by jasondibenedetto** [comment]
@ScriptSmith Thanks for confirming this behaviour. Maybe we can add this to the FAQs.
