### ISSUE TITLE
[FEATURE] Top/recent hashtag flag

### ISSUE THREAD

**Issue by mttwlkr** [ScriptSmith/instamancer#4]
**Is your feature request related to a problem? Please describe.**
No, this tool is amazing. Thank you.

**Describe the solution you'd like**
Have a flag that allows scraping hashtags from either top posts, or most recent.

**Comment by ScriptSmith** [comment]
This is related to #3 

Instamancer is built to gather data from requests by default. This tool is intended to be used as part of larger automated data pipelines, and given the nature of web scraping is more focused on stability than completeness.

However there is a clear interest in scraping the data directly from the webpage, so I will add a flag to enable this, but it won't be the default option.

**Comment by ScriptSmith** [comment]
[Version 1.4.0](https://github.com/ScriptSmith/instamancer/releases/tag/v1.4.0) now scrapes the posts already included on the page when `--full` mode is enabled.

**Comment by mttwlkr** [comment]
> [Version 1.4.0](https://github.com/ScriptSmith/instamancer/releases/tag/v1.4.0) now scrapes the posts already included on the page when `--full` mode is enabled.

Thank you! Again, awesome tool. Cheers.
