### ISSUE TITLE
Scraped: 0 in production server

### ISSUE THREAD

**Issue by ihenvyr** [ScriptSmith/instamancer#44]
Hi there, the script worked perfectly well on the production server until yesterday. No problem on my development machine, in production currently it scrapes nothing. Is it possible that the server was blocked by Instagram? Is there a recommended production configuration to avoid being blocked by Instagram? Thank you.

**Comment by ScriptSmith** [comment]
Instagram has recently begun blocking requests from popular cloud providers. This is likely what happened to you in your production instance.

I am not aware of any workarounds other than using network connections that Instagram doesn't block.

**Comment by edsu** [comment]
@ScriptSmith Was this in the news anywhere? How did you hear about the block?

**Comment by ScriptSmith** [comment]
There wasn't any reporting on this as far as I'm aware, but it seems pretty clear given the following:

- My scheduled instamancer jobs stopped working on the same day, in both GCP and AWS
- At the same time, I received identical reports from users such as yourself
- Instamancer no longer works even from new connections using these providers
