### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kaipingchen** [ScriptSmith/instamancer#50]
**Describe the bug**
Discrepancy between posts collected on the instamancer command with different parameters

**To Reproduce**
Steps to reproduce the behavior.

I noticed a discrepancy between how many posts I can collect between the command: instamancer user science.sam --type=csv and instamancer user science.sam -fvd. I performed these two command line on July 21st. 
 
The first command allows me to collect 501 posts which does not include around 10 recent posts of this user, while the second command allows me to collect all of the 512 posts by the user. However, I really like the csv format and I thought the first command should allow me to collect all of this user’s posts, right? 

**Expected behavior**
I thought that the two command lines should allow me to collect the same amount of posts.

**Output**
If applicable, add Instamancer's output in a code block

```
here
```

**Setup (please complete the following information):**
 - MacOS
 - Instamancer version [v1.1.4]
 - Node version [e.g. v11.6.0]
 - NPM version (if applicable) [eg. 6.5.0]

**Additional context**

**Comment by ScriptSmith** [comment]
Full mode retrieves posts not just from the API, as it also includes the posts pre-rendered on the page. There isn't a way to start from the very beginning of the API without modifying the pagination; so to simplify things, I just restricted that functionality to full mode only.
