### ISSUE TITLE
Is it possible to download only the first slide from post that have multiple?

### ISSUE THREAD

**Issue by rosnaib11** [ScriptSmith/instamancer#56]
There's a scenario that a post can be multiple but unfortunately those additional videos are promotion which I don't like to include in download.

![image](https://user-images.githubusercontent.com/26837762/95952145-29584c80-0e2a-11eb-89fa-671d9de662aa.png)

**Comment by ScriptSmith** [comment]
Not possible in the CLI. You could implement something like this in JavaScript.
