### ISSUE TITLE
Write to data file on the fly?

### ISSUE THREAD

**Issue by simonlindgren** [ScriptSmith/instamancer#57]
The way I understand it, Instamancer first runs an entire scrape (and downloads media as it goes, depending on settings). But it is only when the full scrape is done that it writes to json, csv or similar.

So, if running a scrape to get unlimited posts for a hashtag, when will the data file be written? And where does the json/csv data go if the job breaks? Is it only stored in RAM until the end of the run?

**Comment by ScriptSmith** [comment]
By default the data is stored in memory until the scraping is complete; if the job breaks, then it won't be written.

To avoid this, you can stream the data to stdout as it's downloaded by setting the output file to `-` (eg. `-o -`)

And you can pipe stdout to a file with `>`:

```
instamancer hashtag puppies -c10 -o - > puppies.json
```

**Comment by simonlindgren** [comment]
Thanks. Lovely!
